apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00a9dae9e479c55fa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs
spec:
  volumeName: expense-efs
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  #nodeSelector:
    #topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: expense-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: expense-efs
    persistentVolumeClaim:
      claimName: expense-efs
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: 
    purpose: efs-static
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80