kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00a9dae9e479c55fa
  directoryPerms: "700"
  basePath: "/expense" # optional
  